import Head from 'next/head'
import Navbar from '../component/Navbar/Navbar'
import Banner from '../component/Banner/Banner'
import Slider from '../component/Slider/Slider'
import Offer from '../component/Offer/Offer'

export default function Home() {
  return (
    <div>
      {' '}
      <Head>
        <title>Boka</title>
        <meta
          name="salon and beauty booking"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Slider />
      <Offer />
    </div>
  )
}
